// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} solutionId
 * @param {$models.AddEnvironmentRequest} req
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AddEnvironment(solutionId, req) {
    let $resultPromise = /** @type {any} */($Call.ByID(255261038, solutionId, req));
    return $resultPromise;
}

/**
 * @param {string} solutionId
 * @returns {Promise<$models.Environment[]> & { cancel(): void }}
 */
export function GetEnvironments(solutionId) {
    let $resultPromise = /** @type {any} */($Call.ByID(2528114680, solutionId));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} id
 * @returns {Promise<$models.Solution | null> & { cancel(): void }}
 */
export function GetSolution(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(4002103797, id));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<$models.Solution[]> & { cancel(): void }}
 */
export function GetSolutions() {
    let $resultPromise = /** @type {any} */($Call.ByID(188229106));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.Environment.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Solution.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
